### ISSUE TITLE
Waking up cases doesn't work

### ISSUE THREAD

**Issue by greole** [greole/foamMon#7]
If an active case stopped running, restarting the case does not trigger it to be active again

**Comment by dolphguin** [comment]
It has probably to do with this issue. Findings after upgrading foamMon:
1. I copied the tutorials under my $FOAM_RUN path.
2. I started a certain simulation e.g. $FOAM_RUN/incompressible/pimpleFoam/RAS/pitzDaily
3. I was able to monitor it using foamMon from any parent directory
4. I closed foamMon
4. Once the simulation finished, I re-opened foamMon (same path), but I was not able to keep monitoring it (it disappeared from the list)

Furthermore:
1. started another simulation e.g. $FOAM_RUN/multiphase/compressibleInterFoam/laminar/depthCharge2D
2. I could only monitor it with foamMon from $FOAM_RUN/multiphase/compressibleInterFoam/laminar/depthCharge2D or from $FOAM_RUN/multiphase/compressibleInterFoam/laminar.
3. It was not possible to monitor it from parent dictionaries such as $FOAM_RUN or $FOAM_RUN/tutorials
4. Previously finished simulation keeps not appearing in the list
5. At a certain time foamMon stopped refreshing the info and got frozen (probably when the simulation finished). foamM's last screen still shows the simulation in an unfinished stage.
6. (related to #3 ) At this point (frozen), the resource consumption of foamMon is about 40% of the max. processor load.
7. Reopening it either from $FOAM_RUN/multiphase/compressibleInterFoam/laminar/depthCharge2D or from $FOAM_RUN/multiphase/compressibleInterFoam/laminar shows the simulation finished. The consumption is the same as above (40%load)
8. Reopening it either from $FOAM_RUN/multiphase/compressibleInterFoam or any parent directory doesn't show any simulation. The consumption is the same as above (40%load)

**Comment by dolphguin** [comment]
I hope this info helps

**Comment by greole** [comment]
@dolphguin Thanks for reporting. I'll have a look into it.
